version: '3.8'

services:
  orderly-queue:
    image: orderly-queue:latest
    build:
      context: .
      dockerfile: Dockerfile
    read_only: true
    volumes:
      - ./config/config.yaml:/config/config.yaml:ro
      - ./.env:/.env:ro
    restart: always
